name: Matrix Workflow
on:
  push:
    branches:
      - main-matrix
jobs:
    build:
        continue-on-error: true # Allow the job to continue even if it fails for some matrix combinations
        runs-on: ${{ matrix['operating-system'] }}
        strategy:
            matrix:
                node-version: [12, 14, 16, 18]
                operating-system: [ubuntu-latest, windows-latest, macos-latest]
                include:
                  - node-version: 22
                    operating-system: ubuntu-latest
                  - node-version: 20
                    operating-system: windows-latest
                exclude:
                  - node-version: 12
                    operating-system: windows-latest
                  - node-version: 14
                    operating-system: macos-latest
        steps:
          - name: Get code
            uses: actions/checkout@v3
          - name: Set up Node.js
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix['node-version'] }}
          - name: Install dependencies
            run: npm ci
          - name: Build website
            run: npm run build